import { afterEach, beforeEach, expect, test } from 'bun:test'
import { mkdir, mkdtemp, rm } from 'node:fs/promises'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { writeConfig } from '../config.ts'
import { renderLedger, renderRequirements } from '../report.ts'
import { runReport } from '../report-cmd.ts'
import type { Element, Requirement } from '../types.ts'

let root: string

beforeEach(async () => {
  root = await mkdtemp(join(tmpdir(), 'migrate-report-'))
  await mkdir(join(root, '.migrate'), { recursive: true })
})

afterEach(async () => {
  await rm(root, { recursive: true, force: true })
})

const ELEMENT: Element = {
  id: 'route-get-api-users',
  surface: 'routes',
  element: 'GET /api/users',
  found_by: ['code', 'nav'],
  disposition: { kind: 'mapped', fr: 'UM-001' },
  refs: [{ kind: 'src', path: 'Controllers/Users.cs', lines: [42, 58] }],
  lens: 'code',
  batch: 'b-1',
  notes: 'first',
}

const REQUIREMENT: Requirement = {
  id: 'UM-001',
  cap: 'user-management',
  requirement: 'List users | paginated',
  actors: 'User',
  objects: 'User',
  rules: '-',
  origin: 'intended',
  confidence: { kind: 'confirmed' },
  citations: [{ kind: 'ledger', id: 'route-get-api-users' }],
  parity: { kind: 'rubric', level: 'high' },
  batch: 'b-1',
}

test('the ledger renders one section per surface with a header banner', () => {
  const md = renderLedger([ELEMENT])
  expect(md).toContain('generated by `migrate report`')
  expect(md).toContain('## routes')
  expect(md).toContain('route-get-api-users')
  expect(md).toContain('mapped:UM-001')
  expect(md).toContain('code,nav')
})

test('a pipe inside a cell is escaped so the table survives', () => {
  const md = renderRequirements([REQUIREMENT])
  expect(md).toContain('List users \\| paginated')
  // Split on unescaped pipes only: a plain split('|') would also split on the
  // \| this test exists to verify, and would always agree with itself.
  const columns = (line: string): number => line.split(/(?<!\\)\|/).length
  const header = md.split('\n').find((l) => l.startsWith('| id '))
  const row = md.split('\n').find((l) => l.includes('UM-001'))
  expect(header).toBeDefined()
  expect(row).toBeDefined()
  expect(columns(row as string)).toBe(columns(header as string))
})

// The assertion above is only worth having if it can actually fail. This
// reproduces, by hand, exactly what renderRequirements would emit if `cell()`
// regressed to not escaping '|' at all: the requirement cell's literal pipe
// stays raw instead of becoming '\|'. A plain line.split('|') would count
// that raw pipe as a column break in BOTH the correctly-escaped and the
// broken case identically (it does not look at the preceding character),
// so it can never distinguish them -- which is why the brief's original
// `line.split('|')` version always agreed with itself regardless of what
// the code did. The unescaped-pipe split used above does not have that
// blind spot: it must report the broken row as having one more column than
// the header, which is exactly what a bug caught by this test looks like.
test('the corrected column-count assertion genuinely fails when pipe-escaping is missing', () => {
  const header =
    '| id | requirement | actors | objects | rules | confidence | origin | citations | parity |'
  const brokenRow =
    '| UM-001 | List users | paginated | User | User | - | confirmed | intended | route-get-api-users | rubric:high |'
  const columns = (line: string): number => line.split(/(?<!\\)\|/).length
  expect(columns(brokenRow)).not.toBe(columns(header))
})

test('confidence and parity render in their grammar form', () => {
  const md = renderRequirements([
    {
      ...REQUIREMENT,
      confidence: { kind: 'queued', queue: 'q-a' },
      parity: { kind: 'rubric', level: 'moderate', queue: 'q-a' },
    },
  ])
  expect(md).toContain('queued:q-a')
  expect(md).toContain('rubric:moderate:q-a')
})

test('an empty store still renders a valid document', () => {
  const md = renderLedger([])
  expect(md).toContain('No surface elements recorded')
})

// report writes generated views next to the store by default, never inside
// the read-only source checkout. assertNotUnderSource throws by design (see
// paths.test.ts and store.test.ts); report-cmd.ts deliberately does not
// catch that throw itself (unlike census-cmd.ts, import-cmd.ts and
// queue-cmd.ts), relying instead on bin/migrate.ts's central error guard to
// turn it into a clean exit-2 diagnostic -- so at this layer the contract
// under test is that runReport rejects, not that it returns 2.
test('report refuses to write when the output directory sits inside the configured source tree', async () => {
  await writeConfig(root, { sourcePath: root, scope: 'all', targetName: 'newapp' })
  await expect(runReport({ root })).rejects.toThrow(/source/)
})
