import type { Adapter, HandoffInput } from '../handoff.ts'
import { buildWorkItems } from '../handoff.ts'
import type { ApplyResult, Completion, Requirement, Throughput, WorkItem } from '../types.ts'

// The marker is the whole identity mechanism for an issue. It sits in the
// body, so one `issue list` resolves every requirement in a single call, and
// it keeps working after handoff.json is lost or was never committed. That is
// why `refs` records only the milestone: with one issue per requirement, a
// stored ref per issue would be N lookups to learn what one list already says,
// and it would be the copy that goes stale.
// Anchored to the START of the body, and paired with a closing fence.
//
// Unanchored, any issue that merely mentioned a marker was claimed as that
// requirement's issue and then overwritten wholesale: an issue whose body said
// "related to <!-- migrate:fr=UM-001 --> which is not this issue" lost a week
// of repro steps on the next handoff. The adapter's own generated body
// advertises the marker, so documenting the mechanism was enough to get
// hijacked. Anchoring means only a body this adapter wrote can be claimed.
const MARKER = /^<!-- migrate:fr=([^\s>]+) -->/
const BODY_END = '<!-- /migrate -->'

type GhIssue = {
  number: number
  title: string
  body: string
  state: string
  closedAt: string | null
}
type GhMilestone = { number: number; title: string }

async function gh(input: HandoffInput, args: string[]): Promise<string> {
  const proc = Bun.spawn([input.ghBin, ...args], {
    cwd: input.root,
    stdout: 'pipe',
    stderr: 'pipe',
  })
  const [out, err] = await Promise.all([
    new Response(proc.stdout).text(),
    new Response(proc.stderr).text(),
  ])
  await proc.exited
  if (proc.exitCode !== 0) {
    // The failure is reported with gh's own stderr rather than a paraphrase:
    // an auth prompt, a rate limit and a missing repo all arrive here and the
    // operator needs to tell them apart.
    throw new Error(`gh ${args[0]} ${args[1] ?? ''} failed: ${err.trim() || out.trim()}`)
  }
  return out
}

function issueTitle(req: Requirement): string {
  return `${req.id} ${req.requirement}`
}

function issueBody(req: Requirement, item: WorkItem): string {
  return [
    `<!-- migrate:fr=${req.id} -->`,
    '',
    `Capability: ${item.title} (${item.key})`,
    '',
    req.requirement,
    '',
    '| field | value |',
    '| --- | --- |',
    `| actors | ${req.actors} |`,
    `| objects | ${req.objects} |`,
    `| rules | ${req.rules} |`,
    `| confidence | ${req.confidence.kind} |`,
    `| origin | ${req.origin} |`,
    '',
    'Emitted by `migrate handoff --adapter github`. The marker above is how a',
    're-run finds this issue again; removing it will produce a duplicate.',
    'Everything above the line below is regenerated on each run; anything you',
    'write beneath it is yours and is preserved.',
    BODY_END,
  ].join('\n')
}

// Everything after the closing fence belongs to whoever wrote it. A re-run
// regenerates the block above it and puts this back byte for byte; without it,
// any human annotation on a migration issue was reverted by the next handoff,
// which made the idempotency claim true only for issues nobody had touched.
// Nothing this function returns is ever generated by the adapter, so a second
// apply over an untouched issue reproduces the body exactly.
function humanTail(body: string): string {
  const at = body.indexOf(BODY_END)
  return at === -1 ? '' : body.slice(at + BODY_END.length)
}

async function listMilestones(input: HandoffInput, slug: string): Promise<GhMilestone[]> {
  const raw = await gh(input, ['api', `repos/${slug}/milestones?state=all`])
  return JSON.parse(raw) as GhMilestone[]
}

// Two capabilities can legitimately share a title; they can never share a
// slug. Keying the milestone on the title collapsed both onto one milestone
// and pointed both refs at it.
function milestoneTitle(item: WorkItem): string {
  return `${item.title} (${item.key})`
}

const ISSUE_LIMIT = 500

async function listIssues(input: HandoffInput): Promise<GhIssue[]> {
  const raw = await gh(input, [
    'issue',
    'list',
    '--state',
    'all',
    '--limit',
    String(ISSUE_LIMIT),
    '--json',
    'number,title,body,state,closedAt',
  ])
  return JSON.parse(raw) as GhIssue[]
}

async function repoSlug(input: HandoffInput): Promise<string> {
  const raw = await gh(input, ['repo', 'view', '--json', 'nameWithOwner'])
  return (JSON.parse(raw) as { nameWithOwner: string }).nameWithOwner
}

function indexByMarker(issues: GhIssue[]): {
  byFr: Map<string, GhIssue>
  duplicates: string[]
} {
  const byFr = new Map<string, GhIssue>()
  const duplicates: string[] = []
  for (const issue of issues) {
    const m = MARKER.exec(issue.body ?? '')
    const fr = m?.[1]
    if (!fr) continue
    // Two issues under one marker used to mean the last silently won, leaving
    // the other to drift stale forever with no diagnostic.
    if (byFr.has(fr)) duplicates.push(fr)
    else byFr.set(fr, issue)
  }
  return { byFr, duplicates }
}

export const github: Adapter = {
  name: 'github',

  async plan(input: HandoffInput): Promise<WorkItem[]> {
    return buildWorkItems(input.capabilities, input.requirements)
  },

  async apply(items: WorkItem[], input: HandoffInput): Promise<ApplyResult> {
    const slug = await repoSlug(input)
    const milestones = await listMilestones(input, slug)
    const byTitle = new Map(milestones.map((m) => [m.title, m]))
    const issues = await listIssues(input)
    if (issues.length >= ISSUE_LIMIT) {
      // The listing is a hard window with no paging. Silently short, every
      // requirement outside it would be re-filed as a duplicate on each run.
      throw new Error(
        `github: the repository returned ${issues.length} issues, at or above the ${ISSUE_LIMIT} listing limit, so existing migration issues may fall outside the window and be duplicated; narrow the repository or raise the limit before re-running`,
      )
    }
    const { byFr, duplicates } = indexByMarker(issues)
    for (const fr of duplicates) {
      process.stderr.write(
        `github: more than one issue carries the marker for ${fr}; only the first is updated, and the others will drift\n`,
      )
    }
    const byId = new Map(input.requirements.map((r) => [r.id, r]))

    const created: string[] = []
    const updated: string[] = []
    const unchanged: string[] = []
    const refs: Record<string, string> = {}

    for (const item of items) {
      let milestoneCreated = false
      let milestone = byTitle.get(milestoneTitle(item))
      if (!milestone) {
        const raw = await gh(input, [
          'api',
          `repos/${slug}/milestones`,
          '-X',
          'POST',
          '-f',
          `title=${milestoneTitle(item)}`,
          '-f',
          `description=${item.body.split('\n')[0] ?? ''}`,
        ])
        milestone = JSON.parse(raw) as GhMilestone
        byTitle.set(milestoneTitle(item), milestone)
        milestoneCreated = true
      }
      refs[item.key] = `milestone:${milestone.number}`

      let touched = false
      for (const fr of item.frs) {
        const req = byId.get(fr)
        if (!req) continue
        const existing = byFr.get(fr)
        // The human tail is carried across, so an update replaces only the
        // block this adapter owns.
        const body = issueBody(req, item) + humanTail(existing?.body ?? '')
        if (!existing) {
          await gh(input, [
            'issue',
            'create',
            '--title',
            issueTitle(req),
            '--body',
            body,
            '--milestone',
            milestoneTitle(item),
          ])
          touched = true
          continue
        }
        if (existing.body !== body) {
          await gh(input, [
            'issue',
            'edit',
            String(existing.number),
            '--body',
            body,
            '--milestone',
            milestoneTitle(item),
          ])
          touched = true
        }
      }

      if (milestoneCreated) created.push(item.key)
      else if (touched) updated.push(item.key)
      else unchanged.push(item.key)
    }

    return { created, updated, unchanged, refs }
  },

  async throughput(input: HandoffInput): Promise<Throughput> {
    const issues = await listIssues(input)
    const known = new Set(input.requirements.map((r) => r.id))
    const completions: Completion[] = []
    // Deduped by requirement: `velocities` divides a completion count by
    // elapsed days, so two closed issues under one marker would inflate the
    // measured delivery rate even though coverage funnels through a Set and
    // would not have noticed.
    const seen = new Set<string>()
    for (const issue of issues) {
      if (issue.state.toUpperCase() !== 'CLOSED') continue
      const fr = MARKER.exec(issue.body ?? '')?.[1]
      if (fr && seen.has(fr)) continue
      // An issue with no marker was filed by someone else and says nothing
      // about this migration; one whose marker names a requirement the store
      // does not have is reported by coverage rather than silently counted.
      if (!fr || !known.has(fr)) continue
      seen.add(fr)
      completions.push({ fr, doneAt: issue.closedAt ? issue.closedAt.slice(0, 10) : null })
    }
    completions.sort((a, b) => a.fr.localeCompare(b.fr))
    return { completions, basis: 'github issues closed, dated from closedAt' }
  },
}
