import { mkdir } from 'node:fs/promises'
import { join } from 'node:path'
import type { Adapter, HandoffInput } from '../handoff.ts'
import { buildWorkItems } from '../handoff.ts'
import { readTextFile, writeAtomically } from '../store.ts'
import type { ApplyResult, Completion, Requirement, Throughput, WorkItem } from '../types.ts'

const OUT_DIR = join('docs', 'migrate')
const CAP_DIR = join(OUT_DIR, 'capabilities')
const ROADMAP = join(OUT_DIR, 'roadmap.md')

// The roadmap's checkbox line is both what this adapter writes and what it
// reads back, so the grammar is stated once and used from both directions.
//
// The date sits in an HTML comment rather than in parentheses after the id.
// Parenthesised, it was indistinguishable from requirement text that happens
// to open with one: a requirement reading "(2026-08-12) Raise an invoice"
// parsed as a dated completion and fed a fabricated date straight into the
// measured velocity, against the roadmap header's own promise that an undated
// tick contributes nothing to the rate. A comment cannot be produced by
// ordinary requirement prose, and an owner adding a date by hand copies the
// form from the line above it.
const LINE = /^- \[([ xX])\] (\S+)(?:\s+<!-- done:(\d{4}-\d{2}-\d{2}) -->)?\s*(.*)$/

export type RoadmapState = Map<string, { checked: boolean; date: string | null }>

export function parseRoadmap(text: string): RoadmapState {
  const state: RoadmapState = new Map()
  for (const line of text.split('\n')) {
    const m = LINE.exec(line.trim())
    if (!m) continue
    const [, box, fr, date] = m
    if (!fr) continue
    state.set(fr, { checked: box?.toLowerCase() === 'x', date: date ?? null })
    // A duplicated id would otherwise let the last line silently win.
  }
  return state
}

function checkboxLine(req: Requirement, state: RoadmapState): string {
  const prior = state.get(req.id)
  const box = prior?.checked ? 'x' : ' '
  const date = prior?.checked && prior.date ? ` <!-- done:${prior.date} -->` : ''
  return `- [${box}] ${req.id}${date} ${req.requirement}`
}

function renderRoadmap(items: WorkItem[], reqs: Requirement[], state: RoadmapState): string {
  const lines = [
    '# Migration roadmap',
    '',
    'Generated by `migrate handoff --adapter markdown`, in dependency order:',
    'a capability appears after every capability it cites.',
    '',
    'Tick a box when the requirement is delivered, and record the date the',
    'same way the line above it does: `<!-- done:YYYY-MM-DD -->` straight',
    'after the id. `migrate coverage` reads this file, and `migrate forecast`',
    'needs the dates, so an undated tick counts as built but contributes',
    'nothing to the measured rate.',
    '',
  ]
  items.forEach((item, i) => {
    const own = reqs.filter((r) => r.cap === item.key)
    lines.push(`## ${i + 1}. ${item.title}`)
    lines.push('')
    lines.push(`Depends on: ${item.dependsOn.length > 0 ? item.dependsOn.join(', ') : 'nothing'}`)
    lines.push(`Detail: ${join(CAP_DIR, `${item.key}.md`)}`)
    lines.push('')
    if (own.length === 0) lines.push('No requirements were extracted for this capability.')
    else for (const r of own) lines.push(checkboxLine(r, state))
    lines.push('')
  })
  return lines.join('\n')
}

function cell(text: string): string {
  return text.replace(/\|/g, '\\|').replace(/\n/g, ' ')
}

function renderCapability(item: WorkItem, reqs: Requirement[]): string {
  const own = reqs.filter((r) => r.cap === item.key)
  const lines = [
    `# ${item.title}`,
    '',
    `- Key: ${item.key}`,
    `- Depends on: ${item.dependsOn.length > 0 ? item.dependsOn.join(', ') : 'nothing'}`,
    `- Requirements: ${item.weight}`,
    '',
    '## Functional requirements',
    '',
    '| id | requirement | actors | objects | rules | confidence | origin |',
    '| --- | --- | --- | --- | --- | --- | --- |',
  ]
  for (const r of own) {
    lines.push(
      `| ${r.id} | ${cell(r.requirement)} | ${cell(r.actors)} | ${cell(r.objects)} | ${cell(r.rules)} | ${r.confidence.kind} | ${r.origin} |`,
    )
  }
  lines.push('')
  return lines.join('\n')
}

async function readIfPresent(path: string): Promise<string | null> {
  try {
    return await readTextFile(path)
  } catch {
    return null
  }
}

export const markdown: Adapter = {
  name: 'markdown',

  async plan(input: HandoffInput): Promise<WorkItem[]> {
    return buildWorkItems(input.capabilities, input.requirements)
  },

  async apply(items: WorkItem[], input: HandoffInput): Promise<ApplyResult> {
    const src = input.config.source.path
    await mkdir(join(input.root, CAP_DIR), { recursive: true })

    // The roadmap is read before it is written, and every ticked box and its
    // date is carried forward. Without this, running handoff a second time to
    // pick up newly extracted requirements would silently erase the owner's
    // record of what has been delivered. Re-running to finish a partial apply
    // is behaviour the degradation contract requires, so it must not be the
    // operation that loses data.
    const roadmapPath = join(input.root, ROADMAP)
    const existingRoadmap = await readIfPresent(roadmapPath)
    const state = existingRoadmap ? parseRoadmap(existingRoadmap) : new Map()

    const created: string[] = []
    const updated: string[] = []
    const unchanged: string[] = []
    const refs: Record<string, string> = {}

    for (const item of items) {
      const rel = join(CAP_DIR, `${item.key}.md`)
      const path = join(input.root, rel)
      const next = renderCapability(item, input.requirements)
      const before = await readIfPresent(path)
      if (before === null) created.push(item.key)
      else if (before !== next) updated.push(item.key)
      else unchanged.push(item.key)
      if (before !== next) await writeAtomically(path, next, src)
      refs[item.key] = rel
    }

    const nextRoadmap = renderRoadmap(items, input.requirements, state)
    if (existingRoadmap !== nextRoadmap) {
      await writeAtomically(roadmapPath, nextRoadmap, src)
      // The roadmap is part of what this adapter emits, so a run that rewrote
      // it has not left everything unchanged. Without this the result could
      // report every item `unchanged` while the roadmap was in fact replaced.
      if (created.length === 0) {
        for (const key of unchanged.splice(0, unchanged.length)) updated.push(key)
      }
    }

    return { created, updated, unchanged, refs }
  },

  async throughput(input: HandoffInput): Promise<Throughput> {
    const text = await readIfPresent(join(input.root, ROADMAP))
    const basis = 'markdown roadmap checkboxes, dated in file'
    if (text === null) return { completions: [], basis }
    const completions: Completion[] = []
    for (const [fr, entry] of parseRoadmap(text)) {
      if (entry.checked) completions.push({ fr, doneAt: entry.date })
    }
    // Sorted by requirement id so two reads of one file agree, and so a
    // coverage figure does not depend on where a line sits in the document.
    completions.sort((a, b) => a.fr.localeCompare(b.fr))
    return { completions, basis }
  },
}
