import type {
  Confidence,
  Disposition,
  Element,
  Parity,
  QueueItem,
  Ref,
  Requirement,
} from './types.ts'

const BANNER = '<!-- generated by `migrate report`; edit the store, not this file -->'

// A cell's content is free text an agent wrote while reading a legacy
// codebase, so it can contain anything. Two things actually break a GFM
// table's structure (change the column count a row parses to, or split one
// row into several): an unescaped '|', which reads as a new column
// boundary, and a line break, which ends the row outright. Both are
// neutralized here: '|' is escaped to '\|', and every line-break variant
// (bare '\n', '\r\n', and a lone '\r' from old Mac-authored text) is
// flattened to a space, not just '\n' alone, so a stray '\r' can't survive
// as an unflattened character in the middle of a row.
//
// A run of backticks is deliberately left alone. It cannot change the
// column count or split the row: GFM splits a table row into cells by its
// literal, unescaped '|' characters first, and only afterward parses each
// cell's inline content (code spans, emphasis, ...) independently, so an
// unbalanced backtick run is confined to the cell it's in and renders as
// literal backticks at worst. Wrapping such a cell in a matching fence was
// considered, but it would have to run after the '|' escaping above, and a
// backtick code span does not itself interpret backslash escapes, so an
// escaped pipe inside it would render as the literal two characters '\|'
// instead of a pipe: a cosmetic regression in exchange for guarding against
// a break that was never structural in the first place.
function cell(text: string): string {
  return text.replaceAll('|', '\\|').replaceAll(/\r\n|\r|\n/g, ' ')
}

export function refToText(ref: Ref): string {
  if (ref.kind === 'src')
    return ref.lines ? `src:${ref.path}:${ref.lines[0]}-${ref.lines[1]}` : `src:${ref.path}`
  if (ref.kind === 'ledger') return ref.id
  if (ref.kind === 'doc') return `doc:${ref.path}`
  return `observed:${ref.host}${ref.path}`
}

export function dispositionToText(d: Disposition): string {
  if (d.kind === 'mapped') return `mapped:${d.fr}`
  if (d.kind === 'out-of-scope') return `out-of-scope:${d.queue}`
  return 'unaccounted'
}

export function confidenceToText(c: Confidence): string {
  return c.kind === 'queued' ? `queued:${c.queue}` : c.kind
}

export function parityToText(p: Parity | null): string {
  if (p === null) return '-'
  if (p.kind === 'rubric')
    return p.level === 'high' ? 'rubric:high' : `rubric:${p.level}:${p.queue}`
  return `${p.kind}:${p.ref}`
}

export function renderLedger(elements: Element[]): string {
  const lines = [BANNER, '', '# Surface ledger', '']
  if (elements.length === 0) {
    lines.push('No surface elements recorded yet.', '')
    return lines.join('\n')
  }
  const bySurface = new Map<string, Element[]>()
  for (const el of elements) {
    const list = bySurface.get(el.surface) ?? []
    list.push(el)
    bySurface.set(el.surface, list)
  }
  for (const surface of [...bySurface.keys()].sort()) {
    lines.push(`## ${surface}`, '')
    lines.push('| id | element | found-by | disposition | refs | notes |')
    lines.push('| --- | --- | --- | --- | --- | --- |')
    for (const el of bySurface.get(surface) ?? []) {
      lines.push(
        `| ${cell(el.id)} | ${cell(el.element)} | ${el.found_by.join(',')} | ${dispositionToText(el.disposition)} | ${cell(el.refs.map(refToText).join(', '))} | ${cell(el.notes)} |`,
      )
    }
    lines.push('')
  }
  return lines.join('\n')
}

export function renderRequirements(reqs: Requirement[]): string {
  const lines = [BANNER, '', '# Functional requirements', '']
  if (reqs.length === 0) {
    lines.push('No requirements recorded yet.', '')
    return lines.join('\n')
  }
  const byCap = new Map<string, Requirement[]>()
  for (const req of reqs) {
    const list = byCap.get(req.cap) ?? []
    list.push(req)
    byCap.set(req.cap, list)
  }
  for (const cap of [...byCap.keys()].sort()) {
    lines.push(`## ${cap}`, '')
    lines.push(
      '| id | requirement | actors | objects | rules | confidence | origin | citations | parity |',
    )
    lines.push('| --- | --- | --- | --- | --- | --- | --- | --- | --- |')
    for (const req of byCap.get(cap) ?? []) {
      lines.push(
        `| ${cell(req.id)} | ${cell(req.requirement)} | ${cell(req.actors)} | ${cell(req.objects)} | ${cell(req.rules)} | ${confidenceToText(req.confidence)} | ${req.origin} | ${cell(req.citations.map(refToText).join(', '))} | ${cell(parityToText(req.parity))} |`,
      )
    }
    lines.push('')
  }
  return lines.join('\n')
}

export function renderQueueReport(items: QueueItem[]): string {
  const lines = [BANNER, '', '# Decision queue', '']
  if (items.length === 0) {
    lines.push('No queue items.', '')
    return lines.join('\n')
  }
  lines.push('| id | severity | status | recommendation |')
  lines.push('| --- | --- | --- | --- |')
  for (const item of items) {
    const first = item.recommendation.split('\n')[0] ?? ''
    lines.push(`| ${cell(item.id)} | ${item.severity} | ${item.status} | ${cell(first)} |`)
  }
  lines.push('')
  return lines.join('\n')
}
